package interpreter

const (
	PARAM_TYPE_INT      = 0x01
	PARAM_TYPE_STRING   = 0x02
	PARAM_TYPE_CARD     = 0x04
	PARAM_TYPE_GROUP    = 0x08
	PARAM_TYPE_EFFECT   = 0x10
	PARAM_TYPE_FUNCTION = 0x20
	PARAM_TYPE_BOOLEAN  = 0x40
	PARAM_TYPE_INDEX    = 0x80

	COROUTINE_FINISH = 1
	COROUTINE_YIELD  = 2
	COROUTINE_ERROR  = 3
)
